### ISSUE TITLE
Building from source?

### ISSUE THREAD

**Issue by HeikoAdams** [Metalnem/runtastic#1]
It would be very helpfull if you could provide information about building the app from source. Especially what dependencies are required.

**Comment by SebastianTs** [comment]
Have you tried `go build main.go` or just `go build` inside the project-path with an proper installed version of go ? (See [golang.org](https://golang.org/doc/install#install) for more information)
The dependencies are listed in the import statement of main.go

**Comment by Metalnem** [comment]
I didn't want to give instructions in README file for building from source on purpose. Primary users of the app are ordinary people who just want to run one command and not have to worry about Go and package dependencies (instructions would probably just confuse them). Sebastian wrote a nice answer to your question, so I'm closing this one.

**Comment by HeikoAdams** [comment]
I asked because there are no binaries for linux and my go-skills are minimal.

**Comment by Metalnem** [comment]
You should have just asked for the Linux binary :) I'll make a Linux build today and put the link in the README file.

**Comment by Metalnem** [comment]
[Here](https://github.com/Metalnem/runtastic/releases/download/v1.6.2/runtastic-linux64-1.6.2.zip) is the Linux version. Enjoy!
