### ISSUE TITLE
Getting Invalid email address or password with correct credentials

### ISSUE THREAD

**Issue by kelps** [Metalnem/runtastic#2]
Getting error F0423 on main.go:137 Invalid email address or password for credentials I am sure are correct.

I just tested the credentials in 3 different browsers running in private mode to be sure it was using what I typed instead of cookies.

Maybe something changed in the Runtastic api you're using or in the way you're passing the credentials.

I was really hoping to be able to use this to export my Runtastic activities to Strava.

**Comment by SebastianTs** [comment]
The current version worked a couple of minutes ago, so the runtastic api has not changed.

Maybe it is an encoding issue - Do you use any special characters for your mail or password ?

**Comment by kelps** [comment]
No special characters in the email or password. I even changed the password to a very simple one to be sure that wasn't the problem.

I am in Brazil. Does the code do anything with dates or decimal numbers to encode the credentials? Maybe it could be picking up my regional settings and formating something wrong. 

BTW, I'm running on a Windows 10 Creators Update.

**Comment by kelps** [comment]
Nevermind about the login error. It was my mistake. I was using the correct password but the wrong email for the login (I was trying to log in with the email I used on Strava).

It just finished downloading. 547 activities. It looked like it had frozen (no feedback on screen and not CPU load on Task Manager), but it worked and created the zip file. I suppose the CPU usage is low because most of the time is spent waiting for web requests. Would be good to have some indication that it is working (showing a summary of how many activities will be downloaded and a countdown every few seconds with how many left). 

Anyway, excellent work and thanks for being so responsive and for creating this. I was about to do my own reverse engineering to accomplish this.

Best regards,

Kelps
