### ISSUE TITLE
TCX files are rejected by Garmin Connect

### ISSUE THREAD

**Issue by DiWa51** [Metalnem/runtastic#3]
Hi,
I've used your tool to export my Runtastic activities in order to import them in Garmin Connect.
I used both gpx and tcx while exporting from Runtastic.
Though when I 1st uploaded tcx files in Garmin Connect they were all rejected ones after the others.
The interface was not really detailing the reason unfortunately.

In the end I have used the gpx format successfully (though it might loose the extra information that TCX holds)

This issue didn't block me (and I'm not expecting a fix), though for other users of your script, there might be checks to perform on the tcx output format to make sure it is still compatible with Garmin schema (which cant be found anymore / 404 by the way...)

Thanks again

**Comment by Metalnem** [comment]
I tried importing my activities to Connect, but it worked. Could you send my one of your tcx files that are failing?

**Comment by DiWa51** [comment]
This is one file failing on the upload:
[runtastic-running-tcx.zip](https://github.com/Metalnem/runtastic/files/956176/runtastic-running-tcx.zip)
Thanks

**Comment by Metalnem** [comment]
Thanks, I will investigate.
