### ISSUE TITLE
Can't login with facebook credentials

### ISSUE THREAD

**Issue by mschindl** [Metalnem/runtastic#8]
Did you test your app with facebook credentials? I can't login with facebook credentials.
I use the OSX version.

**Comment by mipapo** [comment]
That's not possible as the facebook authentication flow cannot work in that way with this script

**Comment by mschindl** [comment]
Do you know how I can convert my profile to a normal profile?

**Comment by mipapo** [comment]
It should be possible to set a password at the runtastic website for your account.

**Comment by mschindl** [comment]
You did a great job, because the download method with HTTP doesn't work anymore.

How did I convert my FB login?
1. change mail address
2. reset password of new mailaddress

After that your app works very well.

Thank you
