### ISSUE TITLE
Password with exclamation mark

### ISSUE THREAD

**Issue by hlszk** [Metalnem/runtastic#9]
Passwords with exclamation marks doesn't get escaped.

I get the following error: `zsh: event not found: ` _rest of password after exclamation mark_.
Changing the password did the trick.

Thank you for your work!

**Comment by Metalnem** [comment]
Hi Agata,

Exclamation mark is special character for the shell (zsh in your case). You have to escape the password with either double or single quotation marks ("!pass123" or '!pass123').

**Comment by hlszk** [comment]
Hi MetaInem,

Escaping with both kinds of quotation marks was rejecting the password in both zsh and bash. Solution is mentioned in first post.
